version: "3.8"

services:
  python:
      build: .
      image: "leandroauzier/insight"
      command: pip3 install -r requirements.txt
  django:
      build: .
      container_name: django
      command: python manage.py runserver 0.0.0.0:7000
      tty: true
      volumes:
        - .:/app/
      ports:
        - "7000:7000"
      environment:
        - DEBUG=1
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
        - CELERY_BROKER=redis://redis:6379
        - CELERY_BACKEND=redis://redis:6379
      depends_on:
        - redis
  celery:
      build: .
      command: sh -c "celery -A setup worker -l INFO & celery -A setup beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
      volumes:
        - .:/app/
      environment:
        - DEBUG=1
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
        - CELERY_BROKER=redis://redis:6379
        - CELERY_BACKEND=redis://redis:6379
      depends_on:
        - django
        - redis
  redis:
      image: "redis:alpine"
      volumes:
      - .:/app/
  #oracle:
