version: "3.8"

services:
  django:
    build: .
    container_name: django
    command: bash -c "python manage.py migrate && python manage.py loaddata db.json && python manage.py runserver 0.0.0.0:8000"
    tty: true
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    image: clusterdesenvolvimento/insight:DistribuidoraEstrela
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A setup worker -l INFO & celery -A setup beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    #command: sh -c "celery -A setup worker -l INFO --concurrency=5 -n worker1@%h & celery -A setup worker -l INFO --concurrency=5 -n worker2@%h & celery -A setup worker -l INFO --concurrency=5 -n worker3@%h & celery -A setup worker -l INFO --concurrency=5 -n worker4@%h & celery -A setup beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - .:/code/
    depends_on:
      - django
      - redis
  redis:
    image: "redis:alpine"
#    container_name: redis
#    command: sh -c "redis-server"

volumes:
  - .:/code/
