version: "3.8"

services:

  django:
      build: .
      container_name: django
      command: python manage.py runserver 0.0.0.0:7000
      tty: true
      volumes:
        - .:/code/
      ports:
        - "7000:7000"
      environment:
        - DEBUG=1
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
        - CELERY_BROKER=redis://redis:6379
        - CELERY_BACKEND=redis://redis:6379
      image: leandroauzier/insight:BrasilMed
      depends_on:
        - redis
  celery:
      build: .
      command: sh -c "celery -A setup worker -l INFO --concurrency=5 -n worker1@%h & celery -A setup worker -l INFO --concurrency=5 -n worker2@%h & celery -A setup worker -l INFO --concurrency=5 -n worker3@%h & celery -A setup worker -l INFO --concurrency=5 -n worker4@%h & celery -A setup beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
      container_name: celery
      volumes:
        - .:/code/
      environment:
        - DEBUG=1
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
        - CELERY_BROKER=redis://redis:6379
        - CELERY_BACKEND=redis://redis:6379
      depends_on:
        - django
        - redis
  redis:
      image: "redis:alpine"
      volumes:
      - .:/code/
