# Generated by Django 2.2.23 on 2022-01-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=84, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('empresa', models.CharField(blank=True, max_length=84, null=True)),
                ('empresa_id', models.CharField(blank=True, max_length=84, null=True)),
                ('enable_tasks', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
