# Generated by Django 2.2.23 on 2022-02-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='db_password',
            field=models.CharField(blank=True, max_length=84, null=True, verbose_name='Senha do BD'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='db_service',
            field=models.CharField(blank=True, max_length=84, null=True, verbose_name='Service do BD'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='db_user',
            field=models.CharField(blank=True, max_length=84, null=True, verbose_name='Usuário do BD'),
        ),
    ]
